server:
  port: 8090
spring:
  datasource:
    password:
    url: jdbc:mysql://localhost:3306/sales?serverTimezone=UTC
    username: root
  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      client:
        registration:
         google:
          clientId: xxxxxxx xxxxxx xxxxxx
          clientSecret: xxxxxxx xxxxxx xxxxxx
          scope:
           - email
           - profile